addSbtPlugin("com.47deg"                 % "sbt-microsites"          % "0.9.7")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"          % "1.3.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"           % "1.6.1")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"             % "0.4.3")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                 % "0.3.7")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"              % "5.3.1")
addSbtPlugin("io.chrisdavenport"         % "sbt-mima-version-check"  % "0.1.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"            % "0.1.10")