addSbtPlugin("com.jsuereth"       % "sbt-pgp"        % "1.0.1")
addSbtPlugin("com.github.gseitz"  % "sbt-release"    % "1.0.3")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"   % "0.5.0")
addSbtPlugin("com.47deg"          % "sbt-microsites" % "0.6.1")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"    % "0.3.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.2.27")
