// Copyright (c) 2013-2020 Rob Norris and Contributors
// This software is licensed under the MIT License (MIT).
// For more information see LICENSE or https://opensource.org/licenses/MIT

package doobie

@deprecated(message = "Use package doobie.enumerated instead.", since = "0.10.0")
object `enum` {

  type AutoGeneratedKeys = doobie.enumerated.AutoGeneratedKeys
  val AutoGeneratedKeys = doobie.enumerated.AutoGeneratedKeys

  type ColumnNullable = doobie.enumerated.ColumnNullable
  val ColumnNullable = doobie.enumerated.ColumnNullable

  type FetchDirection = doobie.enumerated.FetchDirection
  val FetchDirection = doobie.enumerated.FetchDirection

  type Holdability = doobie.enumerated.Holdability
  val Holdability = doobie.enumerated.Holdability

  type JdbcType = doobie.enumerated.JdbcType
  val JdbcType = doobie.enumerated.JdbcType

  type Nullability = doobie.enumerated.Nullability
  val Nullability = doobie.enumerated.Nullability

  type ParameterMode = doobie.enumerated.ParameterMode
  val ParameterMode = doobie.enumerated.ParameterMode

  type ParameterNullable = doobie.enumerated.ParameterNullable
  val ParameterNullable = doobie.enumerated.ParameterNullable

  type ResultSetConcurrency = doobie.enumerated.ResultSetConcurrency
  val ResultSetConcurrency = doobie.enumerated.ResultSetConcurrency

  type ResultSetType = doobie.enumerated.ResultSetType
  val ResultSetType = doobie.enumerated.ResultSetType

  type TransactionIsolation = doobie.enumerated.TransactionIsolation
  val TransactionIsolation = doobie.enumerated.TransactionIsolation

}
